import Head from "next/head";
import Banner from "@/shared/organisms/banner";
import Services from "@/shared/organisms/services";
import Events from "@/shared/organisms/events";
import Testimonials from "@/shared/organisms/testimonials";
import Footer from "@/shared/organisms/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Banner />
        <Services />
        <Events />
        <Testimonials />
        <Footer />
      </>
    </>
  );
}
